version: '3.8'

services:
  test-db:
    image: postgres
    ports:
      - 8080:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db